# Generated by Django 4.1.5 on 2023-01-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='location',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
